<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest" Version="3.6.4" />
    <PackageReference Include="Syncfusion.Xamarin.Core" Version="30.2.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WpfApp1\WpfApp1.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="EntityFramework">
      <HintPath>..\..\..\..\..\Downloads\EntityFramework.dll</HintPath>
    </Reference>
    <Reference Include="EntityFramework.SqlServer">
      <HintPath>..\..\..\..\..\Downloads\EntityFramework.SqlServer.dll</HintPath>
    </Reference>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="WindowsBase" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
