//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorRoleRequests
    {
        public int RequestID { get; set; }
        public int UserID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
