//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int BookingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> SeatID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Seats Seats { get; set; }
        public virtual Sessions Sessions { get; set; }
        public virtual Users Users { get; set; }
    }
}
